version: '3.8'

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - '5432:5432'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
    driver: local
